import AppKit
import Combine
import Foundation
import os.log

/// Watches NSPasteboard, maintains history, persists to disk, writes items back to the pasteboard.
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    /// Set when Clip itself writes to the pasteboard so we don't re-record our own paste.
    private var ignoreNextChange = false

    private let storageURL: URL = {
        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Clip", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("history.json")
    }()

    // Standard identifiers from nspasteboard.org — password managers (1Password etc.)
    // mark sensitive/transient content with these types. We must skip them.
    private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    init() {
        load()
    }

    // MARK: - Monitoring

    private let log = Logger(subsystem: "com.rajparmar.Clip", category: "capture")

    func startMonitoring() {
        // NSPasteboard has no change notification on macOS; polling changeCount is the
        // standard approach (Maccy, Pastebot, Raycast all do this). 200ms is responsive
        // yet negligible CPU since we only compare an Int.
        scheduleTimer()

        // Reliability hardening: timers can be stale around sleep/wake, and the
        // category-wide complaint against clipboard managers is silently missed
        // copies. On wake (and on re-activation) force an immediate check and
        // make sure the timer is alive.
        let wsCenter = NSWorkspace.shared.notificationCenter
        wsCenter.addObserver(self, selector: #selector(ensureMonitoring),
                             name: NSWorkspace.didWakeNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(ensureMonitoring),
                                               name: NSApplication.didBecomeActiveNotification,
                                               object: nil)
    }

    private func scheduleTimer() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.2, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        timer?.tolerance = 0.1
        RunLoop.main.add(timer!, forMode: .common)
    }

    @objc private func ensureMonitoring() {
        if timer == nil || !(timer?.isValid ?? false) {
            log.warning("capture timer was dead — restarting")
            scheduleTimer()
        }
        checkPasteboard()
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func checkPasteboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        if pb.changeCount > lastChangeCount + 1 {
            // More than one copy happened inside a poll window; we can only see
            // the latest. Log it so misses are measurable, not mysterious.
            log.info("changeCount jumped by \(pb.changeCount - self.lastChangeCount) — intermediate copy not captured")
        }
        lastChangeCount = pb.changeCount

        if ignoreNextChange {
            ignoreNextChange = false
            return
        }

        // Privacy: skip concealed/transient content (passwords, auto-generated data).
        let types = pb.types ?? []
        if Preferences.shared.ignoreConcealed &&
            (types.contains(concealedType) || types.contains(transientType) || types.contains(autoGeneratedType)) {
            return
        }

        // Per-app ignore list.
        let frontApp = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontApp?.bundleIdentifier,
           Preferences.shared.ignoredApps.contains(bundleID) {
            return
        }

        guard let item = makeItem(from: pb, sourceApp: frontApp) else { return }
        add(item)
    }

    private func makeItem(from pb: NSPasteboard, sourceApp: NSRunningApplication?) -> ClipboardItem? {
        let bundleID = sourceApp?.bundleIdentifier
        let appName = sourceApp?.localizedName

        // File URLs first (Finder copies provide both file URLs and an icon image).
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return ClipboardItem(content: .fileURLs(urls.map(\.path)),
                                 sourceAppBundleID: bundleID, sourceAppName: appName)
        }

        // Text (capture RTF/HTML alongside for formatted paste).
        if let text = pb.string(forType: .string), !text.isEmpty {
            guard Preferences.shared.maxItemLength == 0 || text.count <= Preferences.shared.maxItemLength else { return nil }
            return ClipboardItem(content: .text(text),
                                 sourceAppBundleID: bundleID, sourceAppName: appName,
                                 rtfData: pb.data(forType: .rtf),
                                 htmlData: pb.data(forType: .html))
        }

        // Images.
        if Preferences.shared.captureImages,
           let imageData = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            let png: Data
            if pb.data(forType: .png) != nil {
                png = imageData
            } else if let rep = NSBitmapImageRep(data: imageData),
                      let converted = rep.representation(using: .png, properties: [:]) {
                png = converted
            } else {
                return nil
            }
            // Cap stored image size at 10 MB to keep history file sane.
            guard png.count <= 10_000_000 else { return nil }
            return ClipboardItem(content: .image(png),
                                 sourceAppBundleID: bundleID, sourceAppName: appName)
        }

        return nil
    }

    // MARK: - Mutations

    private func add(_ item: ClipboardItem) {
        DispatchQueue.main.async {
            // De-duplicate: if identical content exists, move it to top (preserving pin state).
            if let existingIndex = self.items.firstIndex(where: { $0.content == item.content }) {
                var existing = self.items.remove(at: existingIndex)
                existing.copiedAt = Date()
                existing.sourceAppBundleID = item.sourceAppBundleID
                existing.sourceAppName = item.sourceAppName
                self.items.insert(existing, at: 0)
            } else {
                self.items.insert(item, at: 0)
                LinkMetadataFetcher.shared.enrich(item, in: self)
            }
            self.trim()
            self.save()
        }
    }

    /// Called back by LinkMetadataFetcher once a URL's title/icon arrive.
    func applyLinkMetadata(itemID: UUID, title: String?, iconPNG: Data?) {
        guard let idx = items.firstIndex(where: { $0.id == itemID }) else { return }
        items[idx].linkTitle = title
        items[idx].linkIconPNG = iconPNG
        save()
    }

    func togglePin(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[idx].isPinned.toggle()
        save()
    }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        save()
    }

    func clearHistory(keepPinned: Bool) {
        if keepPinned {
            items.removeAll { !$0.isPinned }
        } else {
            items.removeAll()
        }
        save()
    }

    private func trim() {
        let max = Preferences.shared.historyLimit
        guard max > 0 else { return }
        let unpinned = items.filter { !$0.isPinned }
        if unpinned.count > max {
            let toRemove = Set(unpinned.suffix(unpinned.count - max).map(\.id))
            items.removeAll { toRemove.contains($0.id) }
        }
    }

    // MARK: - Writing back to pasteboard

    /// Copies the item to the system pasteboard. If `plainTextOnly`, strips formatting.
    func copyToPasteboard(_ item: ClipboardItem, plainTextOnly: Bool = false) {
        let pb = NSPasteboard.general
        ignoreNextChange = true
        pb.clearContents()

        switch item.content {
        case .text(let s):
            pb.setString(s, forType: .string)
            if !plainTextOnly {
                if let rtf = item.rtfData { pb.setData(rtf, forType: .rtf) }
                if let html = item.htmlData { pb.setData(html, forType: .html) }
            }
        case .image(let data):
            pb.setData(data, forType: .png)
        case .fileURLs(let paths):
            let urls = paths.map { URL(fileURLWithPath: $0) as NSURL }
            pb.writeObjects(urls)
        }
    }

    // MARK: - Persistence

    private func save() {
        let snapshot = items
        DispatchQueue.global(qos: .utility).async { [storageURL] in
            do {
                let data = try JSONEncoder().encode(snapshot)
                try data.write(to: storageURL, options: .atomic)
                // History can contain sensitive text — owner-only file permissions.
                try? FileManager.default.setAttributes([.posixPermissions: 0o600],
                                                       ofItemAtPath: storageURL.path)
            } catch {
                NSLog("Clip: failed to save history: \(error)")
            }
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: storageURL),
              let decoded = try? JSONDecoder().decode([ClipboardItem].self, from: data) else { return }
        items = decoded
    }
}
