import AppKit
import Combine
import Foundation
import os.log

/// Watches NSPasteboard, maintains history, persists via the SQLite engine,
/// writes items back to the pasteboard.
///
/// `items` is the *working set* (all pinned + the most recent unpinned items)
/// — enough for instant browsing. Search goes through `search(_:)`, which
/// queries the full, unlimited history in the database.
/// What's on the system clipboard right now — for the inspector strip.
struct ClipboardSummary: Equatable {
    var systemImage: String
    var preview: String
    var detail: String
}

final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []
    @Published private(set) var categories: [ClipCategory] = []
    @Published private(set) var currentClipboard: ClipboardSummary?

    let engine = SQLiteStore()
    static let workingSetLimit = 1_000

    private var timer: Timer?
    private var retentionTimer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    /// Set when Clip itself writes to the pasteboard so we don't re-record our own paste.
    private var ignoreNextChange = false

    // Standard identifiers from nspasteboard.org — password managers (1Password etc.)
    // mark sensitive/transient content with these types. We must skip them.
    private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    init() {
        refreshWorkingSet()
        categories = engine.fetchCategories()
        applyRetention()
        trashCount = engine.trashCount()
    }

    // MARK: - Categories

    var collectingCategory: ClipCategory? { categories.first { $0.isCollecting } }

    func addCategory(name: String, colorHex: String) {
        let category = ClipCategory(name: name, colorHex: colorHex,
                                    sortOrder: (categories.map(\.sortOrder).max() ?? 0) + 1)
        engine.saveCategory(category)
        categories = engine.fetchCategories()
    }

    func renameCategory(_ category: ClipCategory, to name: String) {
        var updated = category
        updated.name = name
        engine.saveCategory(updated)
        categories = engine.fetchCategories()
    }

    func deleteCategory(_ category: ClipCategory) {
        engine.deleteCategory(id: category.id)
        categories = engine.fetchCategories()
        refreshWorkingSet()
    }

    /// Toggle collect mode. Only one category collects at a time.
    func setCollecting(_ category: ClipCategory?, enabled: Bool) {
        engine.setCollecting(categoryID: enabled ? category?.id : nil)
        categories = engine.fetchCategories()
    }

    func assign(_ item: ClipboardItem, to category: ClipCategory?) {
        engine.setCategory(itemID: item.id, categoryID: category?.id)
        if let idx = items.firstIndex(where: { $0.id == item.id }) {
            items[idx].categoryID = category?.id
        }
    }

    func items(in category: ClipCategory) -> [ClipboardItem] {
        engine.fetchItems(categoryID: category.id)
    }

    /// Look up a single live item (used by quick-paste hotkeys). Checks the
    /// in-memory working set first, falls back to the database.
    func item(withID id: UUID) -> ClipboardItem? {
        items.first { $0.id == id } ?? engine.fetchItem(id: id)
    }

    /// Quick edit: rewrite a text item's content before pasting it.
    func updateText(_ item: ClipboardItem, to newText: String) {
        engine.updateText(id: item.id, newText: newText)
        if let idx = items.firstIndex(where: { $0.id == item.id }) {
            items[idx].content = .text(newText)
            items[idx].rtfData = nil
            items[idx].htmlData = nil
            items[idx].linkTitle = nil
            items[idx].linkIconPNG = nil
        }
    }

    private func refreshWorkingSet() {
        items = engine.fetchWorkingSet(recentLimit: Self.workingSetLimit)
    }

    /// Full-history search (FTS). Empty query returns the working set.
    func search(_ query: String) -> [ClipboardItem] {
        let q = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !q.isEmpty else { return items }
        return engine.search(q)
    }

    func applyRetention() {
        let p = Preferences.shared
        engine.applyRetention(maxItems: p.historyLimit,
                              maxAgeDays: p.retentionDays,
                              imageMaxAgeDays: p.imageRetentionDays)
        engine.purgeExpiredTrash(olderThanDays: 30)
        trashCount = engine.trashCount()
        refreshWorkingSet()
        // Re-run daily so age-based expiry actually expires things.
        if retentionTimer == nil {
            retentionTimer = Timer.scheduledTimer(withTimeInterval: 6 * 3600, repeats: true) { [weak self] _ in
                self?.applyRetention()
                self?.refreshWorkingSet()
            }
            retentionTimer?.tolerance = 600
        }
    }

    // MARK: - Monitoring

    private let log = Logger(subsystem: "com.rajparmar.Clip", category: "capture")

    func startMonitoring() {
        // NSPasteboard has no change notification on macOS; polling changeCount is the
        // standard approach (Maccy, Pastebot, Raycast all do this). 200ms is responsive
        // yet negligible CPU since we only compare an Int.
        scheduleTimer()
        currentClipboard = summarize(NSPasteboard.general)

        // Reliability hardening: timers can be stale around sleep/wake, and the
        // category-wide complaint against clipboard managers is silently missed
        // copies. On wake (and on re-activation) force an immediate check and
        // make sure the timer is alive.
        let wsCenter = NSWorkspace.shared.notificationCenter
        wsCenter.addObserver(self, selector: #selector(ensureMonitoring),
                             name: NSWorkspace.didWakeNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(ensureMonitoring),
                                               name: NSApplication.didBecomeActiveNotification,
                                               object: nil)
    }

    private func scheduleTimer() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.2, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        timer?.tolerance = 0.1
        RunLoop.main.add(timer!, forMode: .common)
    }

    @objc private func ensureMonitoring() {
        if timer == nil || !(timer?.isValid ?? false) {
            log.warning("capture timer was dead — restarting")
            scheduleTimer()
        }
        checkPasteboard()
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func summarize(_ pb: NSPasteboard) -> ClipboardSummary? {
        if let s = pb.string(forType: .string), !s.isEmpty {
            let line = s.trimmingCharacters(in: .whitespacesAndNewlines)
                .split(separator: "\n", maxSplits: 1).first.map(String.init) ?? ""
            return ClipboardSummary(systemImage: "text.alignleft",
                                    preview: String(line.prefix(70)),
                                    detail: "\(s.count) characters")
        }
        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let name = (urls[0].path as NSString).lastPathComponent
            return ClipboardSummary(systemImage: "doc",
                                    preview: urls.count == 1 ? name : "\(urls.count) files",
                                    detail: "file\(urls.count == 1 ? "" : "s")")
        }
        if let data = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            return ClipboardSummary(systemImage: "photo",
                                    preview: "Image",
                                    detail: ByteCountFormatter.string(fromByteCount: Int64(data.count),
                                                                      countStyle: .file))
        }
        if (pb.types ?? []).isEmpty { return nil }
        return ClipboardSummary(systemImage: "questionmark.square.dashed",
                                preview: "Other content", detail: "")
    }

    /// Empties the system clipboard (inspector's Clear action).
    func clearSystemClipboard() {
        ignoreNextChange = true
        NSPasteboard.general.clearContents()
        currentClipboard = nil
    }

    /// Largest image (in bytes) Clip will store — shared by pasteboard image
    /// capture and screenshot capture so behavior is consistent.
    static let maxImageBytes = 10_000_000

    /// Screenshot watcher entry point: file lands in history (dedup-aware via
    /// content hash, OCR runs automatically) and optionally onto the clipboard.
    func addScreenshot(png: Data) {
        // Honor the same gates as normal image capture: respect the image
        // toggle and the shared size cap, so screenshots aren't a back door.
        guard Preferences.shared.captureImages, png.count <= Self.maxImageBytes else { return }

        let item = ClipboardItem(content: .image(png), sourceAppName: "Screenshot")
        add(item)
        if Preferences.shared.screenshotAutoCopy {
            ignoreNextChange = true
            let pb = NSPasteboard.general
            pb.clearContents()
            pb.setData(png, forType: .png)
            currentClipboard = summarize(pb)
        }
    }

    private func checkPasteboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        currentClipboard = summarize(pb)
        if pb.changeCount > lastChangeCount + 1 {
            // More than one copy happened inside a poll window; we can only see
            // the latest. Log it so misses are measurable, not mysterious.
            log.info("changeCount jumped by \(pb.changeCount - self.lastChangeCount) — intermediate copy not captured")
        }
        lastChangeCount = pb.changeCount

        if ignoreNextChange {
            ignoreNextChange = false
            return
        }

        // Privacy: skip concealed/transient content (passwords, auto-generated data).
        let types = pb.types ?? []
        if Preferences.shared.ignoreConcealed &&
            (types.contains(concealedType) || types.contains(transientType) || types.contains(autoGeneratedType)) {
            return
        }

        // Per-app ignore list.
        let frontApp = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontApp?.bundleIdentifier,
           Preferences.shared.ignoredApps.contains(bundleID) {
            return
        }

        guard let item = makeItem(from: pb, sourceApp: frontApp) else { return }
        add(item)
    }

    private func makeItem(from pb: NSPasteboard, sourceApp: NSRunningApplication?) -> ClipboardItem? {
        let bundleID = sourceApp?.bundleIdentifier
        let appName = sourceApp?.localizedName

        // File URLs first (Finder copies provide both file URLs and an icon image).
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return ClipboardItem(content: .fileURLs(urls.map(\.path)),
                                 sourceAppBundleID: bundleID, sourceAppName: appName)
        }

        // Text (capture RTF/HTML alongside for formatted paste).
        if let text = pb.string(forType: .string), !text.isEmpty {
            guard Preferences.shared.maxItemLength == 0 || text.count <= Preferences.shared.maxItemLength else { return nil }
            return ClipboardItem(content: .text(text),
                                 sourceAppBundleID: bundleID, sourceAppName: appName,
                                 rtfData: pb.data(forType: .rtf),
                                 htmlData: pb.data(forType: .html))
        }

        // Images.
        if Preferences.shared.captureImages,
           let imageData = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            let png: Data
            if pb.data(forType: .png) != nil {
                png = imageData
            } else if let rep = NSBitmapImageRep(data: imageData),
                      let converted = rep.representation(using: .png, properties: [:]) {
                png = converted
            } else {
                return nil
            }
            // Cap stored image size to keep history file sane (shared cap).
            guard png.count <= Self.maxImageBytes else { return nil }
            return ClipboardItem(content: .image(png),
                                 sourceAppBundleID: bundleID, sourceAppName: appName)
        }

        return nil
    }

    // MARK: - Mutations

    private func add(_ item: ClipboardItem) {
        DispatchQueue.main.async {
            var incoming = item
            // Collect mode: file every new copy into the collecting category.
            if let collecting = self.collectingCategory {
                incoming.categoryID = collecting.id
            }
            // Engine dedups by content hash: identical content keeps its row
            // (and pin state) and just gets fresher recency.
            let isNew = !self.items.contains { $0.content == incoming.content }
            var stored = self.engine.upsert(incoming)
            if let collecting = self.collectingCategory, stored.categoryID == nil {
                // Dedup returned an existing row — file that one too.
                self.engine.setCategory(itemID: stored.id, categoryID: collecting.id)
                stored.categoryID = collecting.id
            }

            // Update the in-memory working set without a full refetch.
            self.items.removeAll { $0.id == stored.id }
            let insertAt = self.items.prefix(while: { $0.isPinned && !stored.isPinned }).count
            self.items.insert(stored, at: min(insertAt, self.items.count))
            if self.items.count > Self.workingSetLimit + 200 {
                self.refreshWorkingSet()
            }

            if isNew {
                LinkMetadataFetcher.shared.enrich(stored, in: self)
                self.runOCRIfNeeded(on: stored)
            }
            // Re-copying trashed content rescues it; keep the badge accurate.
            self.trashCount = self.engine.trashCount()

            // A real copy means the user's intent changed — lets the paste
            // queue cancel its session.
            NotificationCenter.default.post(name: .clipExternalCopy, object: nil)
        }
    }

    /// On-device OCR for captured images; recognized text becomes searchable.
    private func runOCRIfNeeded(on item: ClipboardItem) {
        guard Preferences.shared.ocrImages,
              case .image = item.content,
              item.ocrText == nil,
              let fullImage = engine.loadFullImage(for: item) else { return }
        OCRService.recognizeText(in: fullImage) { [weak self] text in
            guard let self, let text else { return }
            self.engine.setOCRText(id: item.id, text: text)
            if let idx = self.items.firstIndex(where: { $0.id == item.id }) {
                self.items[idx].ocrText = text
            }
        }
    }

    /// Paste-time transform: loads the pasteboard with the transformed text
    /// without altering the stored item.
    func copyTransformed(_ item: ClipboardItem, transform: TextTransform) {
        guard case .text(let s) = item.content else { return }
        let pb = NSPasteboard.general
        ignoreNextChange = true
        pb.clearContents()
        pb.setString(transform.apply(to: s), forType: .string)
    }

    /// Called back by LinkMetadataFetcher once a URL's title/icon arrive.
    func applyLinkMetadata(itemID: UUID, title: String?, iconPNG: Data?) {
        engine.setLinkMetadata(id: itemID, title: title, iconPNG: iconPNG)
        guard let idx = items.firstIndex(where: { $0.id == itemID }) else { return }
        items[idx].linkTitle = title
        items[idx].linkIconPNG = iconPNG
    }

    func togglePin(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else {
            // Item came from a deep search result outside the working set.
            engine.setPinned(!item.isPinned, id: item.id)
            refreshWorkingSet()
            return
        }
        items[idx].isPinned.toggle()
        engine.setPinned(items[idx].isPinned, id: item.id)
    }

    /// Soft delete — the item moves to the Trash (recoverable for 30 days).
    func delete(_ item: ClipboardItem) {
        engine.delete(id: item.id)
        items.removeAll { $0.id == item.id }
        trashDidChange()
    }

    func clearHistory(keepPinned: Bool) {
        engine.clear(keepPinned: keepPinned)
        refreshWorkingSet()
        trashDidChange()
    }

    // MARK: - Trash

    @Published private(set) var trashCount = 0

    func trashItems() -> [ClipboardItem] {
        engine.fetchTrash()
    }

    func restore(_ item: ClipboardItem) {
        engine.restore(id: item.id)
        refreshWorkingSet()
        trashDidChange()
    }

    func deleteForever(_ item: ClipboardItem) {
        engine.purge(id: item.id)
        trashDidChange()
    }

    func emptyTrash() {
        engine.emptyTrash()
        trashDidChange()
    }

    private func trashDidChange() {
        trashCount = engine.trashCount()
    }

    // MARK: - Writing back to pasteboard

    /// Copies the item to the system pasteboard. If `plainTextOnly`, strips formatting.
    func copyToPasteboard(_ item: ClipboardItem, plainTextOnly: Bool = false) {
        let pb = NSPasteboard.general
        ignoreNextChange = true
        pb.clearContents()

        switch item.content {
        case .text(let s):
            pb.setString(s, forType: .string)
            if !plainTextOnly {
                if let rtf = item.rtfData { pb.setData(rtf, forType: .rtf) }
                if let html = item.htmlData { pb.setData(html, forType: .html) }
            }
        case .image:
            // Large images live on disk; paste the full-resolution original.
            if let full = engine.loadFullImage(for: item) {
                pb.setData(full, forType: .png)
            }
        case .fileURLs(let paths):
            let urls = paths.map { URL(fileURLWithPath: $0) as NSURL }
            pb.writeObjects(urls)
        }
    }
}
