import AppKit
import Combine
import Foundation
import os.log

/// Watches NSPasteboard, maintains history, persists via the SQLite engine,
/// writes items back to the pasteboard.
///
/// `items` is the *working set* (all pinned + the most recent unpinned items)
/// — enough for instant browsing. Search goes through `search(_:)`, which
/// queries the full, unlimited history in the database.
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    let engine = SQLiteStore()
    static let workingSetLimit = 1_000

    private var timer: Timer?
    private var retentionTimer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    /// Set when Clip itself writes to the pasteboard so we don't re-record our own paste.
    private var ignoreNextChange = false

    // Standard identifiers from nspasteboard.org — password managers (1Password etc.)
    // mark sensitive/transient content with these types. We must skip them.
    private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    init() {
        refreshWorkingSet()
        applyRetention()
    }

    private func refreshWorkingSet() {
        items = engine.fetchWorkingSet(recentLimit: Self.workingSetLimit)
    }

    /// Full-history search (FTS). Empty query returns the working set.
    func search(_ query: String) -> [ClipboardItem] {
        let q = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !q.isEmpty else { return items }
        return engine.search(q)
    }

    func applyRetention() {
        let p = Preferences.shared
        engine.applyRetention(maxItems: p.historyLimit,
                              maxAgeDays: p.retentionDays,
                              imageMaxAgeDays: p.imageRetentionDays)
        // Re-run daily so age-based expiry actually expires things.
        if retentionTimer == nil {
            retentionTimer = Timer.scheduledTimer(withTimeInterval: 6 * 3600, repeats: true) { [weak self] _ in
                self?.applyRetention()
                self?.refreshWorkingSet()
            }
            retentionTimer?.tolerance = 600
        }
    }

    // MARK: - Monitoring

    private let log = Logger(subsystem: "com.rajparmar.Clip", category: "capture")

    func startMonitoring() {
        // NSPasteboard has no change notification on macOS; polling changeCount is the
        // standard approach (Maccy, Pastebot, Raycast all do this). 200ms is responsive
        // yet negligible CPU since we only compare an Int.
        scheduleTimer()

        // Reliability hardening: timers can be stale around sleep/wake, and the
        // category-wide complaint against clipboard managers is silently missed
        // copies. On wake (and on re-activation) force an immediate check and
        // make sure the timer is alive.
        let wsCenter = NSWorkspace.shared.notificationCenter
        wsCenter.addObserver(self, selector: #selector(ensureMonitoring),
                             name: NSWorkspace.didWakeNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(ensureMonitoring),
                                               name: NSApplication.didBecomeActiveNotification,
                                               object: nil)
    }

    private func scheduleTimer() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.2, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        timer?.tolerance = 0.1
        RunLoop.main.add(timer!, forMode: .common)
    }

    @objc private func ensureMonitoring() {
        if timer == nil || !(timer?.isValid ?? false) {
            log.warning("capture timer was dead — restarting")
            scheduleTimer()
        }
        checkPasteboard()
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func checkPasteboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        if pb.changeCount > lastChangeCount + 1 {
            // More than one copy happened inside a poll window; we can only see
            // the latest. Log it so misses are measurable, not mysterious.
            log.info("changeCount jumped by \(pb.changeCount - self.lastChangeCount) — intermediate copy not captured")
        }
        lastChangeCount = pb.changeCount

        if ignoreNextChange {
            ignoreNextChange = false
            return
        }

        // Privacy: skip concealed/transient content (passwords, auto-generated data).
        let types = pb.types ?? []
        if Preferences.shared.ignoreConcealed &&
            (types.contains(concealedType) || types.contains(transientType) || types.contains(autoGeneratedType)) {
            return
        }

        // Per-app ignore list.
        let frontApp = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontApp?.bundleIdentifier,
           Preferences.shared.ignoredApps.contains(bundleID) {
            return
        }

        guard let item = makeItem(from: pb, sourceApp: frontApp) else { return }
        add(item)
    }

    private func makeItem(from pb: NSPasteboard, sourceApp: NSRunningApplication?) -> ClipboardItem? {
        let bundleID = sourceApp?.bundleIdentifier
        let appName = sourceApp?.localizedName

        // File URLs first (Finder copies provide both file URLs and an icon image).
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return ClipboardItem(content: .fileURLs(urls.map(\.path)),
                                 sourceAppBundleID: bundleID, sourceAppName: appName)
        }

        // Text (capture RTF/HTML alongside for formatted paste).
        if let text = pb.string(forType: .string), !text.isEmpty {
            guard Preferences.shared.maxItemLength == 0 || text.count <= Preferences.shared.maxItemLength else { return nil }
            return ClipboardItem(content: .text(text),
                                 sourceAppBundleID: bundleID, sourceAppName: appName,
                                 rtfData: pb.data(forType: .rtf),
                                 htmlData: pb.data(forType: .html))
        }

        // Images.
        if Preferences.shared.captureImages,
           let imageData = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            let png: Data
            if pb.data(forType: .png) != nil {
                png = imageData
            } else if let rep = NSBitmapImageRep(data: imageData),
                      let converted = rep.representation(using: .png, properties: [:]) {
                png = converted
            } else {
                return nil
            }
            // Cap stored image size at 10 MB to keep history file sane.
            guard png.count <= 10_000_000 else { return nil }
            return ClipboardItem(content: .image(png),
                                 sourceAppBundleID: bundleID, sourceAppName: appName)
        }

        return nil
    }

    // MARK: - Mutations

    private func add(_ item: ClipboardItem) {
        DispatchQueue.main.async {
            // Engine dedups by content hash: identical content keeps its row
            // (and pin state) and just gets fresher recency.
            let isNew = !self.items.contains { $0.content == item.content }
            let stored = self.engine.upsert(item)

            // Update the in-memory working set without a full refetch.
            self.items.removeAll { $0.id == stored.id }
            let insertAt = self.items.prefix(while: { $0.isPinned && !stored.isPinned }).count
            self.items.insert(stored, at: min(insertAt, self.items.count))
            if self.items.count > Self.workingSetLimit + 200 {
                self.refreshWorkingSet()
            }

            if isNew {
                LinkMetadataFetcher.shared.enrich(stored, in: self)
            }
        }
    }

    /// Called back by LinkMetadataFetcher once a URL's title/icon arrive.
    func applyLinkMetadata(itemID: UUID, title: String?, iconPNG: Data?) {
        engine.setLinkMetadata(id: itemID, title: title, iconPNG: iconPNG)
        guard let idx = items.firstIndex(where: { $0.id == itemID }) else { return }
        items[idx].linkTitle = title
        items[idx].linkIconPNG = iconPNG
    }

    func togglePin(_ item: ClipboardItem) {
        guard let idx = items.firstIndex(where: { $0.id == item.id }) else {
            // Item came from a deep search result outside the working set.
            engine.setPinned(!item.isPinned, id: item.id)
            refreshWorkingSet()
            return
        }
        items[idx].isPinned.toggle()
        engine.setPinned(items[idx].isPinned, id: item.id)
    }

    func delete(_ item: ClipboardItem) {
        engine.delete(id: item.id)
        items.removeAll { $0.id == item.id }
    }

    func clearHistory(keepPinned: Bool) {
        engine.clear(keepPinned: keepPinned)
        refreshWorkingSet()
    }

    // MARK: - Writing back to pasteboard

    /// Copies the item to the system pasteboard. If `plainTextOnly`, strips formatting.
    func copyToPasteboard(_ item: ClipboardItem, plainTextOnly: Bool = false) {
        let pb = NSPasteboard.general
        ignoreNextChange = true
        pb.clearContents()

        switch item.content {
        case .text(let s):
            pb.setString(s, forType: .string)
            if !plainTextOnly {
                if let rtf = item.rtfData { pb.setData(rtf, forType: .rtf) }
                if let html = item.htmlData { pb.setData(html, forType: .html) }
            }
        case .image:
            // Large images live on disk; paste the full-resolution original.
            if let full = engine.loadFullImage(for: item) {
                pb.setData(full, forType: .png)
            }
        case .fileURLs(let paths):
            let urls = paths.map { URL(fileURLWithPath: $0) as NSURL }
            pb.writeObjects(urls)
        }
    }
}
